import{FeatureTracker}from'./features.js';import{Sensors}from'./sensors.js';import{ObjectiveTranslator}from'./translator.js';import{WorldRenderer}from'./renderer.js';
const $=id=>document.getElementById(id),video=$('cam'),ov=$('overlay'),oc=ov.getContext('2d'),WR=new WorldRenderer($('world')),S=new Sensors();
let F,T,K,W,H,stream,running=false,busy=false,log=[],cameraSettings=null,lastProcess=0;
function status(t,c='warn'){$('state').textContent=t;$('state').className='state '+c}
async function start(){try{await S.start();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});video.srcObject=stream;await video.play();await new Promise(r=>setTimeout(r,160));const tr=stream.getVideoTracks()[0];cameraSettings=tr.getSettings?tr.getSettings():{};const vw=video.videoWidth||cameraSettings.width||720,vh=video.videoHeight||cameraSettings.height||1280;W=320;H=Math.round(W*vh/vw);K={fx:265,fy:265,cx:W/2,cy:H/2};F=new FeatureTracker(W,H);T=new ObjectiveTranslator(K);S.onOrientation=s=>T.onOrientation(s);S.onMotion=(s,t)=>T.onMotion(s,t);running=true;status('INITIALIZING GLOBAL LOCK','warn');schedule()}catch(e){status('START FAILED: '+e.message,'bad');$('debug').textContent=e.stack||e}}
function schedule(){if(!running)return;if('requestVideoFrameCallback'in video)video.requestVideoFrameCallback(frame);else requestAnimationFrame(t=>frame(t,{}))}
function frame(now,meta){if(busy){schedule();return}busy=true;try{const t=performance.now();if(t-lastProcess<28){return}lastProcess=t;const r=F.process(video),obs=F.observations(250),o=T.frame(obs,t);
 $('lock').textContent=o.globalLock?'LOCKED':'WAIT';$('imu').textContent=o.imuCalibrated?'CALIBRATED':'QUIET CAL';$('authority').textContent=o.authority;$('scale').textContent=o.scaleState+(o.scale?` · ${o.scale.toFixed(3)} m/u`:'');$('keyframes').textContent=o.keyframes;$('map').textContent=o.mapSize;$('qualified').textContent=o.qualifiedLandmarks;$('pnp').textContent=o.pnpUsed||0;$('rms').textContent=o.pnpRms==null?'—':o.pnpRms.toFixed(2)+' px';$('parallax').textContent=o.parallax==null?'—':o.parallax.toFixed(2)+' px';$('inliers').textContent=o.inliers||0;
 const p=o.metricPosition;['x','y','z'].forEach((k,i)=>$(k).textContent=p?p[i].toFixed(3)+' m':'—');
 const good=o.scaleState==='METRIC LOCKED'&&o.authority.includes('METRIC');status(good?'METRIC WORLD POSE ACTIVE':o.stage,good?'good':o.globalLock?'warn':'bad');
 $('phase').textContent=o.scaleState==='METRIC LOCKED'?'Metric scale resolved; map pose drives virtual world.':o.imuCalibrated?'Move naturally; keyframes + IMU are solving metric scale.':'Hold normally for a moment while quiet-state IMU bias is learned.';
 WR.draw(o,K,W,H);drawTracks(r.tracks);log.push({t,stage:o.stage,authority:o.authority,scale:o.scale,scaleState:o.scaleState,pVis:o.visualPosition,pMetric:o.metricPosition,map:o.mapSize,pnp:o.pnpUsed,rms:o.pnpRms,parallax:o.parallax,inliers:o.inliers});if(log.length>3000)log.splice(0,500);$('debug').textContent=JSON.stringify(log.at(-1),null,2)
 }catch(e){status('TRANSLATOR ERROR: '+e.message,'bad');$('debug').textContent=e.stack||e}finally{busy=false;schedule()}}
function drawTracks(tracks){ov.width=innerWidth*devicePixelRatio;ov.height=innerHeight*devicePixelRatio;oc.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);oc.clearRect(0,0,innerWidth,innerHeight);const sx=innerWidth/W,sy=innerHeight/H;oc.strokeStyle='rgba(80,255,145,.55)';for(const q of tracks.slice(0,180)){oc.beginPath();oc.moveTo(q.prevX*sx,q.prevY*sy);oc.lineTo(q.x*sx,q.y*sy);oc.stroke()}}
function reset(){if(T){T.reset();F.reset();log=[];status('WORLD RESET','warn')}}
function exp(){const payload={format:'CRUXTAIN_TRANSLATOR_DIAGNOSTICS',version:'1.0',created:new Date().toISOString(),camera:cameraSettings,K,log};const b=new Blob([JSON.stringify(payload)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='CRUXTAIN_Translator_Diagnostics.json';document.body.appendChild(a);a.click();a.remove()}
$('start').onclick=()=>{if(!running)start()};$('reset').onclick=reset;$('export').onclick=exp;$('dbg').onclick=()=>$('hud').classList.toggle('debug');
