function grayFromRGBA(data,w,h,out){for(let i=0,j=0;i<w*h;i++,j+=4)out[i]=(77*data[j]+150*data[j+1]+29*data[j+2])>>8}
function median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length&1?b[m]:(b[m-1]+b[m])/2}
export function signatureDistance(a,b){if(!a||!b||a.length!==b.length)return Infinity;let s=0;for(let i=0;i<a.length;i++)s+=Math.abs(a[i]-b[i]);return s/a.length}
export class FeatureTracker{
 constructor(w=320,h=180){this.configure(w,h)}
 configure(w,h){this.w=w;this.h=h;this.canvas=document.createElement('canvas');this.canvas.width=w;this.canvas.height=h;this.ctx=this.canvas.getContext('2d',{willReadFrequently:true});this.prev=new Uint8Array(w*h);this.curr=new Uint8Array(w*h);this.points=[];this.initial=false;this.id=1;this.frame=0}
 grab(video){this.ctx.drawImage(video,0,0,this.w,this.h);grayFromRGBA(this.ctx.getImageData(0,0,this.w,this.h).data,this.w,this.h,this.curr)}
 signature(x,y){const out=[],w=this.w,h=this.h;for(let by=-4;by<4;by+=2)for(let bx=-4;bx<4;bx+=2){let s=0,n=0;for(let yy=0;yy<2;yy++)for(let xx=0;xx<2;xx++){const X=Math.max(0,Math.min(w-1,Math.round(x+bx+xx))),Y=Math.max(0,Math.min(h-1,Math.round(y+by+yy)));s+=this.curr[Y*w+X];n++}out.push(Math.round(s/n))}return out}
 detect(img,max=360){const w=this.w,h=this.h,c=[];for(let y=5;y<h-5;y+=2)for(let x=5;x<w-5;x+=2){let sxx=0,syy=0,sxy=0;for(let yy=-2;yy<=2;yy++)for(let xx=-2;xx<=2;xx++){const i=(y+yy)*w+x+xx,gx=img[i+1]-img[i-1],gy=img[i+w]-img[i-w];sxx+=gx*gx;syy+=gy*gy;sxy+=gx*gy}const tr=sxx+syy,det=sxx*syy-sxy*sxy,l=.5*(tr-Math.sqrt(Math.max(0,tr*tr-4*det)));if(l>8500)c.push({x,y,q:l})}c.sort((a,b)=>b.q-a.q);const o=[];for(const p of c){if(o.every(q=>(p.x-q.x)**2+(p.y-q.y)**2>64)){o.push({x:p.x,y:p.y,id:this.id++,age:1,q:p.q,sig:null});if(o.length>=max)break}}return o}
 trackOne(p){const w=this.w,h=this.h,r=3,search=10;if(p.x<r+search||p.y<r+search||p.x>=w-r-search||p.y>=h-r-search)return null;let best=1e30,bx=0,by=0,second=1e30;for(let dy=-search;dy<=search;dy++)for(let dx=-search;dx<=search;dx++){let s=0;for(let yy=-r;yy<=r;yy++){let a=(p.y+yy)*w+p.x-r,b=(p.y+dy+yy)*w+p.x+dx-r;for(let xx=-r;xx<=r;xx++){const d=this.prev[a++]-this.curr[b++];s+=d*d}}if(s<best){second=best;best=s;bx=dx;by=dy}else if(s<second)second=s}if(best>9500||best/(second||1)>.93)return null;return{x:p.x+bx,y:p.y+by,id:p.id,age:p.age+1,prevX:p.x,prevY:p.y,error:best,ratio:best/(second||1)}}
 process(video){this.frame++;this.grab(video);if(!this.initial){this.points=this.detect(this.curr);for(const p of this.points)p.sig=this.signature(p.x,p.y);this.prev.set(this.curr);this.initial=true;return{detected:this.points.length,tracks:[],points:this.points,motionPx:0,seeded:this.points.length}}let tracks=[];for(const p of this.points){const q=this.trackOne(p);if(q){q.sig=this.signature(q.x,q.y);tracks.push(q)}}const disp=tracks.map(q=>Math.hypot(q.x-q.prevX,q.y-q.prevY)),motionPx=median(disp);let next=tracks.map(q=>({x:q.x,y:q.y,id:q.id,age:q.age,sig:q.sig}));let seeded=0;if(next.length<200){const fresh=this.detect(this.curr,360);for(const p of fresh){if(next.every(q=>(p.x-q.x)**2+(p.y-q.y)**2>81)){p.sig=this.signature(p.x,p.y);next.push(p);seeded++;if(next.length>=360)break}}}this.points=next;this.prev.set(this.curr);return{detected:next.length,tracks,points:next,motionPx,newFrame:true,seeded}}
 reset(){this.initial=false;this.points=[];this.id=1;this.frame=0}
}
