import{I3,mm,mv,tr,rodrigues,norm,cross,dot,scale,add,sub,symEig,solve}from'./linalg.js';
const D2R=Math.PI/180;
export const DEFAULT_AXIS_MAP=[-1,0,0, 0,1,0, 0,0,1];
export function cameraFromDevice(v){return[v[0],-v[1],-v[2]]}
export function mapRate(raw,M=DEFAULT_AXIS_MAP){return[(M[0]*raw[0]+M[1]*raw[1]+M[2]*raw[2])*D2R,(M[3]*raw[0]+M[4]*raw[1]+M[5]*raw[2])*D2R,(M[6]*raw[0]+M[7]*raw[1]+M[8]*raw[2])*D2R]}
export function integrateGyro(buffer,t0,t1,offsetMs=-90,M=DEFAULT_AXIS_MAP,biasG=[0,0,0]){const a=t0+offsetMs,b=t1+offsetMs;if(!(b>a))return I3();const s=buffer.filter(x=>x.t>=a-25&&x.t<=b+25);if(s.length<2)return I3();let R=I3();for(let i=1;i<s.length;i++){const ta=Math.max(a,s[i-1].t),tb=Math.min(b,s[i].t),dt=(tb-ta)/1000;if(dt<=0)continue;const w0=mapRate(s[i-1].rate.map((v,k)=>v-biasG[k]),M),w1=mapRate(s[i].rate.map((v,k)=>v-biasG[k]),M),w=w0.map((v,k)=>(v+w1[k])*.5*dt);R=mm(rodrigues(w),R,3,3,3)}return R}
function basisColumns(r,u,f){return[r[0],u[0],f[0],r[1],u[1],f[1],r[2],u[2],f[2]]}
export function initialWorldCamera(gravityDevice,headingDeg){const gC=cameraFromDevice(gravityDevice),upC=scale(gC,-1/(norm(gC)||1)),f0=[0,0,1];let fC=sub(f0,scale(upC,dot(f0,upC)));let nf=norm(fC);if(nf<.15){fC.splice(0,3,...[0,-1,0]);nf=1}for(let i=0;i<3;i++)fC[i]/=nf;let rC=cross(upC,fC),nr=norm(rC)||1;rC=rC.map(v=>v/nr);fC=cross(rC,upC);const h=(headingDeg||0)*D2R,upW=[0,1,0],fW=[Math.sin(h),0,Math.cos(h)],rW=cross(upW,fW);const BC=basisColumns(rC,upC,fC),BW=basisColumns(rW,upW,fW);return mm(BW,tr(BC,3,3),3,3,3)}
export function correctGravity(Rwc,gravityDevice,gain=.035){const upC=scale(cameraFromDevice(gravityDevice),-1/(norm(gravityDevice)||1)),pred=mv(Rwc,upC,3,3),target=[0,1,0],axis=cross(pred,target),a=norm(axis);if(a<1e-7)return Rwc;const d=axis.map(v=>v/a*Math.min(.06,a*gain));return mm(rodrigues(d),Rwc,3,3,3)}
export class BiasEstimator{constructor(){this.reset()}reset(){this.samples=[];this.biasA=[0,0,0];this.biasG=[0,0,0];this.ready=false;this.locked=false}push(s){if(this.locked)return;if(Math.hypot(...s.accel)<.35&&Math.hypot(...s.rate)<5){this.samples.push(s);if(this.samples.length>180)this.samples.shift()}if(this.samples.length>=90){const med=k=>{const a=this.samples.map(s=>s[k[0]][k[1]]).sort((x,y)=>x-y),m=a.length>>1;return a[m]};this.biasA=[0,1,2].map(i=>med(['accel',i]));this.biasG=[0,1,2].map(i=>med(['rate',i]));this.ready=true;this.locked=true}}}
export function preintegrateLinear(buffer,t0,t1,Rwc0,offsetMs=-90,M=DEFAULT_AXIS_MAP,biasA=[0,0,0],biasG=[0,0,0]){const a=t0+offsetMs,b=t1+offsetMs,s=buffer.filter(x=>x.t>=a-20&&x.t<=b+20);if(s.length<2)return null;let R=Rwc0.slice(),beta=[0,0,0],alpha=[0,0,0],elapsed=0;for(let i=1;i<s.length;i++){const ta=Math.max(a,s[i-1].t),tb=Math.min(b,s[i].t),dt=(tb-ta)/1000;if(dt<=0)continue;const w0=mapRate(s[i-1].rate.map((v,k)=>v-biasG[k]),M),w1=mapRate(s[i].rate.map((v,k)=>v-biasG[k]),M),w=w0.map((v,k)=>(v+w1[k])*.5*dt);R=mm(R,tr(rodrigues(w),3,3),3,3,3);const ad=s[i].accel.map((v,k)=>v-biasA[k]),aW=mv(R,cameraFromDevice(ad),3,3);alpha=add(alpha,add(scale(beta,dt),scale(aW,.5*dt*dt)));beta=add(beta,scale(aW,dt));elapsed+=dt}return{dt:elapsed,alpha,beta}}
export class ScaleInitializer{
 constructor(){this.intervals=[];this.history=[];this.scale=null;this.state='UNRESOLVED'}
 reset(){this.intervals=[];this.history=[];this.scale=null;this.state='UNRESOLVED'}
 addInterval(dpVisual,pre){if(!pre||pre.dt<.08)return null;this.intervals.push({d:dpVisual,dt:pre.dt,alpha:pre.alpha,beta:pre.beta});if(this.intervals.length>8)this.intervals.shift();return this.solve()}
 solve(){const N=this.intervals.length;if(N<3){this.state='OBSERVING';return null}const n=1+3*(N+1),rows=[],rhs=[];const addRow=(coef,b)=>{rows.push(coef);rhs.push(b)};for(let i=0;i<N;i++){const q=this.intervals[i],vi=1+3*i,vj=1+3*(i+1);for(let k=0;k<3;k++){let c=new Array(n).fill(0);c[0]=q.d[k];c[vi+k]=-q.dt;addRow(c,q.alpha[k]);c=new Array(n).fill(0);c[vj+k]=1;c[vi+k]=-1;addRow(c,q.beta[k])}}const H=new Array(n*n).fill(0),g=new Array(n).fill(0);for(let r=0;r<rows.length;r++)for(let i=0;i<n;i++){g[i]+=rows[r][i]*rhs[r];for(let j=0;j<n;j++)H[i*n+j]+=rows[r][i]*rows[r][j]}for(let i=0;i<n;i++)H[i*n+i]+=1e-7;const x=solve(H,g,n);if(!x)return null;let se=0;for(let r=0;r<rows.length;r++){let y=0;for(let i=0;i<n;i++)y+=rows[r][i]*x[i];se+=(y-rhs[r])**2}const rms=Math.sqrt(se/rows.length),s=x[0];const eig=symEig(H,n).map(e=>Math.max(1e-12,e.value)),cond=Math.max(...eig)/Math.min(...eig);const excite=this.intervals.reduce((z,q)=>z+norm(q.beta),0)/N;const candidate=Number.isFinite(s)&&s>0.015&&s<8&&rms<.18&&cond<1e10&&excite>.025;if(candidate){this.history.push(s);if(this.history.length>5)this.history.shift();if(this.history.length>=3){const mean=this.history.reduce((a,b)=>a+b,0)/this.history.length,sd=Math.sqrt(this.history.reduce((a,b)=>a+(b-mean)**2,0)/this.history.length);if(sd/mean<.18){this.scale=mean;this.state='LOCKED'}else this.state='CANDIDATE'}else this.state='CANDIDATE'}else this.state='OBSERVING';return{scale:s,rms,condition:cond,excitation:excite,state:this.state,lockedScale:this.scale}}
}
