export const I3=()=>[1,0,0,0,1,0,0,0,1];
export const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0); export const norm=a=>Math.hypot(...a); export const add=(a,b)=>a.map((v,i)=>v+b[i]); export const sub=(a,b)=>a.map((v,i)=>v-b[i]); export const scale=(a,s)=>a.map(v=>v*s); export const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
export function mm(A,B,m,n,p){const C=new Array(m*p).fill(0);for(let i=0;i<m;i++)for(let k=0;k<n;k++){const a=A[i*n+k];for(let j=0;j<p;j++)C[i*p+j]+=a*B[k*p+j]}return C} export function mv(A,v,m,n){const o=new Array(m).fill(0);for(let i=0;i<m;i++)for(let j=0;j<n;j++)o[i]+=A[i*n+j]*v[j];return o} export function tr(A,m,n){const T=new Array(A.length);for(let i=0;i<m;i++)for(let j=0;j<n;j++)T[j*m+i]=A[i*n+j];return T}
export function inv3(a){const d=a[0]*(a[4]*a[8]-a[5]*a[7])-a[1]*(a[3]*a[8]-a[5]*a[6])+a[2]*(a[3]*a[7]-a[4]*a[6]);if(Math.abs(d)<1e-12)return null;return[(a[4]*a[8]-a[5]*a[7])/d,(a[2]*a[7]-a[1]*a[8])/d,(a[1]*a[5]-a[2]*a[4])/d,(a[5]*a[6]-a[3]*a[8])/d,(a[0]*a[8]-a[2]*a[6])/d,(a[2]*a[3]-a[0]*a[5])/d,(a[3]*a[7]-a[4]*a[6])/d,(a[1]*a[6]-a[0]*a[7])/d,(a[0]*a[4]-a[1]*a[3])/d]}
export function solve(A,b,n){A=A.slice();b=b.slice();for(let i=0;i<n;i++){let p=i;for(let r=i+1;r<n;r++)if(Math.abs(A[r*n+i])>Math.abs(A[p*n+i]))p=r;if(Math.abs(A[p*n+i])<1e-10)return null;for(let c=i;c<n;c++)[A[i*n+c],A[p*n+c]]=[A[p*n+c],A[i*n+c]];[b[i],b[p]]=[b[p],b[i]];const q=A[i*n+i];for(let c=i;c<n;c++)A[i*n+c]/=q;b[i]/=q;for(let r=0;r<n;r++)if(r!==i){const f=A[r*n+i];for(let c=i;c<n;c++)A[r*n+c]-=f*A[i*n+c];b[r]-=f*b[i]}}return b}
// Jacobi eigensolver for real symmetric matrices. Returns ascending eigenpairs.
export function symEig(A,n,iters=120){A=A.slice();let V=new Array(n*n).fill(0);for(let i=0;i<n;i++)V[i*n+i]=1;for(let it=0;it<iters;it++){let p=0,q=1,best=0;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){const v=Math.abs(A[i*n+j]);if(v>best){best=v;p=i;q=j}}if(best<1e-10)break;const app=A[p*n+p],aqq=A[q*n+q],apq=A[p*n+q],phi=.5*Math.atan2(2*apq,aqq-app),c=Math.cos(phi),s=Math.sin(phi);for(let k=0;k<n;k++){const aik=A[p*n+k],aqk=A[q*n+k];A[p*n+k]=c*aik-s*aqk;A[q*n+k]=s*aik+c*aqk}for(let k=0;k<n;k++){const akp=A[k*n+p],akq=A[k*n+q];A[k*n+p]=c*akp-s*akq;A[k*n+q]=s*akp+c*akq}for(let k=0;k<n;k++){const vip=V[k*n+p],viq=V[k*n+q];V[k*n+p]=c*vip-s*viq;V[k*n+q]=s*vip+c*viq}}
const pairs=Array.from({length:n},(_,i)=>({value:A[i*n+i],vector:Array.from({length:n},(_,r)=>V[r*n+i])})).sort((a,b)=>a.value-b.value);return pairs}
export function svd3(A){const At=tr(A,3,3),AtA=mm(At,A,3,3,3),ep=symEig(AtA,3).sort((a,b)=>b.value-a.value);let V=[];for(let r=0;r<3;r++)for(let c=0;c<3;c++)V.push(ep[c].vector[r]);const S=ep.map(e=>Math.sqrt(Math.max(0,e.value)));let U=new Array(9).fill(0);for(let c=0;c<3;c++){let v=[V[c],V[3+c],V[6+c]],u=mv(A,v,3,3),sn=S[c];if(sn>1e-8)u=u.map(x=>x/sn);else u=c===2?cross([U[0],U[3],U[6]],[U[1],U[4],U[7]]):[0,0,0];const nn=norm(u)||1;u=u.map(x=>x/nn);for(let r=0;r<3;r++)U[r*3+c]=u[r]}if(det3(U)<0)for(let r=0;r<3;r++)U[r*3+2]*=-1;if(det3(V)<0)for(let r=0;r<3;r++)V[r*3+2]*=-1;return{U,S,V}}
export const det3=a=>a[0]*(a[4]*a[8]-a[5]*a[7])-a[1]*(a[3]*a[8]-a[5]*a[6])+a[2]*(a[3]*a[7]-a[4]*a[6]);
export function rodrigues(w){const t=norm(w);if(t<1e-9)return I3();const [x,y,z]=w.map(v=>v/t),c=Math.cos(t),s=Math.sin(t),C=1-c;return[x*x*C+c,x*y*C-z*s,x*z*C+y*s,y*x*C+z*s,y*y*C+c,y*z*C-x*s,z*x*C-y*s,z*y*C+x*s,z*z*C+c]}
