import{signatureDistance}from'./features.js';import{projectWorld,knownRPoseRansac,refinePose6DoF,triangulate,add,mv}from'./geometry.js';
export class LandmarkMap{
 constructor(){this.points=new Map();this.trackIndex=new Map();this.next=1}
 reset(){this.points.clear();this.trackIndex.clear();this.next=1}
 directCorrespondences(points){const out=[];for(const q of points){const mid=this.trackIndex.get(q.id),m=mid?this.points.get(mid):null;if(m)out.push({P:m.P,x:q.x,y:q.y,id:m.id,feature:q,direct:true})}return out}
 match(points,Rwc,p,K){const out=this.directCorrespondences(points),used=new Set(out.map(c=>c.feature.id)),bins=new Map(),B=42;for(const m of this.points.values()){if(!m.confirmed)continue;const z=projectWorld(m.P,Rwc,p,K);if(!z)continue;const bx=Math.floor(z.x/B),by=Math.floor(z.y/B),key=`${bx},${by}`;if(!bins.has(key))bins.set(key,[]);bins.get(key).push({m,z})}for(const q of points){if(used.has(q.id)||!q.sig)continue;const bx=Math.floor(q.x/B),by=Math.floor(q.y/B),cand=[];for(let yy=by-1;yy<=by+1;yy++)for(let xx=bx-1;xx<=bx+1;xx++)cand.push(...(bins.get(`${xx},${yy}`)||[]));let best=null,second=null;for(const z of cand){const dpx=Math.hypot(z.z.x-q.x,z.z.y-q.y);if(dpx>34)continue;const ds=signatureDistance(q.sig,z.m.sig),score=ds+.35*dpx;if(!best||score<best.score){second=best;best={...z,score,ds,dpx}}else if(!second||score<second.score)second={...z,score,ds,dpx}}if(best&&best.ds<34&&(!second||best.score<.78*second.score)){out.push({P:best.m.P,x:q.x,y:q.y,id:best.m.id,feature:q,direct:false});best.m.trackIds.add(q.id);this.trackIndex.set(q.id,best.m.id);best.m.seen=(best.m.seen||0)+1;if(q.sig)best.m.sig=q.sig}}return out}
 solvePose(points,Rwc,pPred,K){const corr=this.match(points,Rwc,pPred,K);const sol=knownRPoseRansac(corr,Rwc,K,28,4);if(!sol)return null;const refined=refinePose6DoF(sol.inliers,Rwc,sol.p,K,9);if(refined&&refined.used>=8&&refined.rms<sol.rms+0.5&&refined.rotationCorrectionDeg<4.0)return{...sol,p:refined.p,Rwc:refined.Rwc,rms:refined.rms,rotationCorrectionDeg:refined.rotationCorrectionDeg,corr};return{...sol,Rwc,rms:sol.rms,rotationCorrectionDeg:0,corr}}
 addTriangulated(key,current,Rrel,trel,RwcKey,pKey,K){let added=0,qualified=0;const currentById=new Map(current.obsEntries||[...current.obs].map(([id,q])=>[id,{id,...q}]));for(const [id,k] of key.obs){const q=currentById.get(id);if(!q)continue;const trk={id,prevX:k.x,prevY:k.y,x:q.x,y:q.y},t=triangulate(trk,Rrel,trel,K);if(!t||!t.positive||t.parallaxDeg<.65||t.error>.18)continue;const Pw=add(pKey,mv(RwcKey,t.P,3,3));let m=null;const mid=this.trackIndex.get(id);if(mid)m=this.points.get(mid);if(!m){m={id:this.next++,P:Pw,sig:q.sig||k.sig,trackIds:new Set([id]),obs:1,seen:1,keyframes:new Set([key.id,current.id]),maxParallax:t.parallaxDeg,error:t.error,confirmed:false};this.points.set(m.id,m);this.trackIndex.set(id,m.id);added++}else{m.obs++;m.seen++;m.keyframes.add(current.id);m.maxParallax=Math.max(m.maxParallax,t.parallaxDeg);m.error=.7*m.error+.3*t.error;m.trackIds.add(id);this.trackIndex.set(id,m.id);if(q.sig)m.sig=q.sig}if(!m.confirmed&&m.obs>=2&&m.keyframes.size>=2&&m.maxParallax>=1.0&&m.error<.16){m.confirmed=true;qualified++}}if(this.points.size>1800){for(const [id,m] of this.points){if(!m.confirmed&&m.obs<2){this.points.delete(id);for(const tid of m.trackIds)if(this.trackIndex.get(tid)===id)this.trackIndex.delete(tid)}if(this.points.size<=1500)break}}return{added,qualified,total:this.points.size,confirmed:[...this.points.values()].filter(m=>m.confirmed).length}}
}
