import{initialWorldCamera,integrateGyro,correctGravity,BiasEstimator,preintegrateLinear,ScaleInitializer}from'./imu.js';
import{OnlineCalibration}from'./calibration.js';
import{derotatedParallax,knownRTranslationRansac,composeRelativePose,rotationAngleDeg,mm,tr,mv,scale,add,sub,norm}from'./geometry.js';
import{LandmarkMap}from'./map.js';
function observations(points){return new Map(points.map(p=>[p.id,{x:p.x,y:p.y,sig:p.sig,age:p.age}]))}
function keyTracks(key,points){const out=[];for(const q of points){const k=key.obs.get(q.id);if(k)out.push({id:q.id,prevX:k.x,prevY:k.y,x:q.x,y:q.y,age:q.age,sig:q.sig})}return out}
export class ObjectiveTranslator{
 constructor(K,sensors){this.K=K;this.sensors=sensors;this.cal=new OnlineCalibration(K.cx*2);this.bias=new BiasEstimator();this.scaleInit=new ScaleInitializer();this.map=new LandmarkMap();this.reset()}
 reset(){this.initialized=false;this.Rwc=null;this.pVisual=[0,0,0];this.key=null;this.keyId=0;this.lastFrameT=null;this.lastFrameR=null;this.lastGood={p:[0,0,0],R:null};this.authority='NONE';this.scaleInit.reset();this.map.reset();this.bias.reset();this.stats={keyframes:0,mapPose:0,translation:0,held:0}}
 ingestMotion(s){this.bias.push(s)}
 init(frameT,points){if(!this.sensors.gravity||this.sensors.heading==null||points.length<35)return false;this.Rwc=initialWorldCamera(this.sensors.gravity,this.sensors.heading);this.pVisual=[0,0,0];this.key={id:++this.keyId,t:frameT,Rwc:this.Rwc.slice(),p:[0,0,0],obs:observations(points)};this.initialized=true;this.lastFrameT=frameT;this.lastFrameR=this.Rwc.slice();this.authority='GLOBAL LOCK';this.stats.keyframes=1;return true}
 update(frameT,result){const points=result.points||[],tracks=result.tracks||[];if(!this.initialized){const ok=this.init(frameT,points);return this.output(ok?'global lock established':'waiting for global lock',result,null,null)}
 const gyroMag=Math.hypot(...this.sensors.rate),accelMag=Math.hypot(...this.sensors.accel);if(this.map.points.size===0)this.cal.maybeUpdate(tracks,this.sensors.motionBuffer,this.lastFrameT,frameT,this.K,accelMag,gyroMag,this.bias.biasG);
 const RprevCurr=integrateGyro(this.sensors.motionBuffer,this.key.t,frameT,this.cal.offsetMs,this.cal.axisMap,this.bias.biasG);let RwcPred=mm(this.key.Rwc,tr(RprevCurr,3,3),3,3,3);RwcPred=correctGravity(RwcPred,this.sensors.gravity);
 let pPred=this.pVisual.slice(),poseSol=null;const mapSol=this.map.solvePose(points,RwcPred,pPred,this.K);if(mapSol&&mapSol.inliers.length>=8&&mapSol.rms<3.8){pPred=mapSol.p;RwcPred=mapSol.Rwc||RwcPred;poseSol=mapSol;this.stats.mapPose++;this.authority=[...this.map.points.values()].some(m=>m.confirmed)?'MAP/PnP':'BOOTSTRAP MAP'}
 const kt=keyTracks(this.key,points),par=derotatedParallax(kt,RprevCurr,this.K),transObservable=kt.length>=16&&par.median>1.1;
 let rel=null,bootstrap=false;if(!poseSol&&transObservable){rel=knownRTranslationRansac(kt,RprevCurr,this.K);if(rel&&rel.inliers.length>=10&&rel.positive>=8){if(this.map.points.size===0){const Ckey=scale(mv(tr(RprevCurr,3,3),rel.t,3,3),-1);pPred=add(this.key.p,mv(this.key.Rwc,Ckey,3,3));bootstrap=true;this.authority='RELATIVE BOOTSTRAP';this.stats.translation++}else{rel=null;this.authority='HOLD: MAP POSE REQUIRED'}}}
 if(!poseSol&&!bootstrap&&!transObservable){this.stats.held++;this.authority='HOLD: NO TRANSLATION EVIDENCE'}
 this.Rwc=RwcPred;this.pVisual=pPred;
 const moved=norm(sub(this.pVisual,this.key.p)),rotDeg=rotationAngleDeg(RprevCurr);let newKey=false,mapGrowth=null,scaleResult=null;if((poseSol||bootstrap)&&(moved>.18||rotDeg>12)&&kt.length>=14){const currentObs=observations(points);const current={id:++this.keyId,t:frameT,Rwc:this.Rwc.slice(),p:this.pVisual.slice(),obs:currentObs,obsEntries:points.map(q=>[q.id,{id:q.id,x:q.x,y:q.y,sig:q.sig,age:q.age}])};const rp=composeRelativePose(this.key.Rwc,this.key.p,current.Rwc,current.p);mapGrowth=this.map.addTriangulated(this.key,current,rp.R,rp.t,this.key.Rwc,this.key.p,this.K);const pre=preintegrateLinear(this.sensors.motionBuffer,this.key.t,frameT,this.key.Rwc,this.cal.offsetMs,this.cal.axisMap,this.bias.biasA,this.bias.biasG);if(pre){scaleResult=this.scaleInit.addInterval(sub(current.p,this.key.p),pre)}this.key=current;this.stats.keyframes++;newKey=true}
 this.lastFrameT=frameT;this.lastFrameR=this.Rwc.slice();return this.output('tracking',result,{parallax:par.median,tracks:kt.length,relative:rel,mapSol,mapGrowth,newKey,scaleResult},poseSol)}
 output(stage,result,extra,poseSol){const s=this.scaleInit.scale,metric=Number.isFinite(s),p=metric?this.pVisual.map(v=>v*s):this.pVisual.slice();return{stage,authority:this.authority,worldLocked:this.initialized,position:p,positionUnits:metric?'m':'visual',visualPosition:this.pVisual.slice(),Rwc:this.Rwc?this.Rwc.slice():null,scaleState:this.scaleInit.state,scale:s,scaleLast:extra?.scaleResult||null,calibration:{offsetMs:this.cal.offsetMs,focal:this.cal.focal,residual:this.cal.bestResidual},bias:{ready:this.bias.ready,accel:this.bias.biasA,gyro:this.bias.biasG},features:result.detected,tracks:result.tracks?.length||0,keyTracks:extra?.tracks||0,parallax:extra?.parallax??0,map:{total:this.map.points.size,confirmed:[...this.map.points.values()].filter(m=>m.confirmed).length,pnpInliers:poseSol?.inliers?.length||0,reprojection:poseSol?.rms??null,rotationCorrectionDeg:poseSol?.rotationCorrectionDeg??0},keyframes:this.stats.keyframes,canDriveVirtual:metric&&this.authority==='MAP/PnP'} }
}
